### ISSUE TITLE
4/1 Feedback TODO

### ISSUE THREAD

**Issue by LaniW** [ECE-366-Final-Project/front_end#39]
The following should be changed on the front_end so far:

- [x] Change the nav bar on each menu page such that each page has a consistent design: Home, Depo/Withdrawal, User Account, 
- [x] If correctly created, the "Create Your Account" button should link to the home page
- [x] Combine User account and transaction history (move to user account)
- [x] Have the current balance at the top of the depo/withdrawal page, have the depo/withdrawal content depicted somewhere below that

**Comment by LaniW** [comment]
All issues above were addressed in previous branches. This was just never closed. #41
